import React from 'react';

const Privacy = () => {
  return (
    <div className="p-6 max-w-3xl mx-auto space-y-8">
      <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
      <p className="text-sm text-gray-500">Last updated: October 17, 2024</p>

      <p className="text-gray-700 leading-relaxed">
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information 
        when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="text-gray-700">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and 
        use of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800">Interpretation and Definitions</h2>

      <h3 className="text-xl font-semibold text-gray-800">Interpretation</h3>
      <p className="text-gray-700">
        The words of which the initial letter is capitalized have meanings defined under the following conditions. 
        The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="text-xl font-semibold text-gray-800">Definitions</h3>
      <p className="text-gray-700">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside space-y-4">
        <li>
          <strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common control with a party, 
          where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote.
        </li>
        <li>
          <strong>Company:</strong> (referred to as either "the Company", "We", "Us", or "Our" in this Agreement) refers to 
          Israel Antunes Neto Desenvolvimento de Software LTDA, Rua Armando Perali, 34, 101.
        </li>
        <li>
          <strong>Cookies:</strong> Small files placed on Your computer or device by a website, containing the details of 
          Your browsing history among other uses.
        </li>
        <li>
          <strong>Country:</strong> Refers to Brazil.
        </li>
        <li>
          <strong>Device:</strong> Any device that can access the Service such as a computer, cellphone, or digital tablet.
        </li>
        <li>
          <strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service:</strong> Refers to the Website.
        </li>
        <li>
          <strong>Service Provider:</strong> Any natural or legal person who processes data on behalf of the Company.
        </li>
        <li>
          <strong>Third-party Social Media Service:</strong> Websites or networks through which a User can log in to the Service.
        </li>
        <li>
          <strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or infrastructure.
        </li>
        <li>
          <strong>Website:</strong> Refers to DrugXpert, accessible from 
          <a href=" https://drugxpert.net/" target="_blank" className="text-blue-600 hover:underline"> drugxpert.net</a>.
        </li>
        <li>
          <strong>You:</strong> The individual accessing the Service, or the company represented by such an individual.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800">Collecting and Using Your Personal Data</h2>

      <h3 className="text-xl font-semibold text-gray-800">Types of Data Collected</h3>

      <h4 className="text-lg font-semibold text-gray-800">Personal Data</h4>
      <p className="text-gray-700">
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can 
        be used to contact or identify You, including but not limited to:
      </p>
      <ul className="list-disc list-inside space-y-2">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold text-gray-800">Usage Data</h4>
      <p className="text-gray-700">
        Usage Data is collected automatically when using the Service. This may include information such as Your IP address, 
        browser type, and the time and date of Your visit.
      </p>

      <h3 className="text-xl font-semibold text-gray-800">Tracking Technologies and Cookies</h3>
      <p className="text-gray-700">
        We use Cookies to track the activity on Our Service. You can instruct Your browser to refuse Cookies or indicate when 
        a Cookie is being sent.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800">Use of Your Personal Data</h2>
      <ul className="list-disc list-inside space-y-4">
        <li><strong>To provide and maintain our Service:</strong> Including monitoring usage.</li>
        <li><strong>To manage Your Account:</strong> Enabling access to functionalities for registered users.</li>
        <li><strong>To contact You:</strong> Regarding updates or service-related issues.</li>
        <li><strong>For other purposes:</strong> Such as data analysis and service improvement.</li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800">Children's Privacy</h2>
      <p className="text-gray-700">
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable 
        information from anyone under 13.
      </p>

      <h2 className="text-2xl font-semibold text-gray-800">Contact Us</h2>
      <p className="text-gray-700">If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul className="list-disc list-inside">
        <li>Email: contact@drugxpert.net</li>
      </ul>
    </div>
  );
}

export default Privacy;
